#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - git
  - openssh-server

users:
  - name: ubuntu
    ssh-authorized-keys:
      - ${ssh_public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
